[build]
    command = "pnpm install && pnpm build"
    publish = "build"

[build.environment]
    NODE_VERSION = "20"
    NODE_ENV = "production"

[[plugins]]
    package = "@netlify/plugin-sveltekit"
