#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/henryvilla/funwork/mysite/portfolio/node_modules/.pnpm/@sveltejs+kit@2.8.5_@sveltejs+vite-plugin-svelte@4.0.2_svelte@5.2.9_vite@5.4.11_@types+node@2_4ajipqgmfnt6e7kwr76cjltssi/node_modules/@sveltejs/kit/node_modules:/Users/henryvilla/funwork/mysite/portfolio/node_modules/.pnpm/@sveltejs+kit@2.8.5_@sveltejs+vite-plugin-svelte@4.0.2_svelte@5.2.9_vite@5.4.11_@types+node@2_4ajipqgmfnt6e7kwr76cjltssi/node_modules/@sveltejs/node_modules:/Users/henryvilla/funwork/mysite/portfolio/node_modules/.pnpm/@sveltejs+kit@2.8.5_@sveltejs+vite-plugin-svelte@4.0.2_svelte@5.2.9_vite@5.4.11_@types+node@2_4ajipqgmfnt6e7kwr76cjltssi/node_modules:/Users/henryvilla/funwork/mysite/portfolio/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/henryvilla/funwork/mysite/portfolio/node_modules/.pnpm/@sveltejs+kit@2.8.5_@sveltejs+vite-plugin-svelte@4.0.2_svelte@5.2.9_vite@5.4.11_@types+node@2_4ajipqgmfnt6e7kwr76cjltssi/node_modules/@sveltejs/kit/node_modules:/Users/henryvilla/funwork/mysite/portfolio/node_modules/.pnpm/@sveltejs+kit@2.8.5_@sveltejs+vite-plugin-svelte@4.0.2_svelte@5.2.9_vite@5.4.11_@types+node@2_4ajipqgmfnt6e7kwr76cjltssi/node_modules/@sveltejs/node_modules:/Users/henryvilla/funwork/mysite/portfolio/node_modules/.pnpm/@sveltejs+kit@2.8.5_@sveltejs+vite-plugin-svelte@4.0.2_svelte@5.2.9_vite@5.4.11_@types+node@2_4ajipqgmfnt6e7kwr76cjltssi/node_modules:/Users/henryvilla/funwork/mysite/portfolio/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../svelte-kit.js" "$@"
else
  exec node  "$basedir/../../svelte-kit.js" "$@"
fi
