#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/henryvilla/funwork/mysite/portfolio/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.0_sass@1.81.0/node_modules/vite/bin/node_modules:/Users/henryvilla/funwork/mysite/portfolio/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.0_sass@1.81.0/node_modules/vite/node_modules:/Users/henryvilla/funwork/mysite/portfolio/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.0_sass@1.81.0/node_modules:/Users/henryvilla/funwork/mysite/portfolio/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/henryvilla/funwork/mysite/portfolio/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.0_sass@1.81.0/node_modules/vite/bin/node_modules:/Users/henryvilla/funwork/mysite/portfolio/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.0_sass@1.81.0/node_modules/vite/node_modules:/Users/henryvilla/funwork/mysite/portfolio/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.0_sass@1.81.0/node_modules:/Users/henryvilla/funwork/mysite/portfolio/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../../vite@5.4.11_@types+node@22.10.0_sass@1.81.0/node_modules/vite/bin/vite.js" "$@"
else
  exec node  "$basedir/../../../../../../vite@5.4.11_@types+node@22.10.0_sass@1.81.0/node_modules/vite/bin/vite.js" "$@"
fi
