const photos = [
	{
		src: '/images/2024/foto-18-2024-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Pentax ME Super',
	},
	{
		src: '/images/2024/foto-17-2024-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Pentax ME Super',
	},
	{
		src: '/images/2024/foto-16-2024-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Pentax ME Super',
	},
	{
		src: '/images/2024/foto-15-2024-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Pentax ME Super',
	},
	{
		src: '/images/2024/foto-14-2024-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Pentax ME Super',
	},
	{
		src: '/images/2024/foto-13-2024-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Pentax ME Super',
	},
	{
		src: '/images/2024/foto-12-2024-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Pentax ME Super',
	},
	{
		src: '/images/2024/foto-11-2024-min.jpg',
		alt: 'Potsdam',
		location: 'Potsdam',
		device: 'Pentax ME Super',
	},
	{
		src: '/images/2024/foto-10-2024-min.jpg',
		alt: 'Potsdam',
		location: 'Potsdam',
		device: 'Pentax ME Super',
	},
	{
		src: '/images/2024/foto-09-2024-min.jpg',
		alt: 'Potsdam',
		location: 'Potsdam',
		device: 'Pentax ME Super',
	},
	{
		src: '/images/2024/foto-08-2024-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Pentax ME Super',
	},
	{
		src: '/images/2024/foto-07-2024-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Pentax ME Super',
	},
	{
		src: '/images/2024/foto-06-2024-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Pentax ME Super',
	},
	{
		src: '/images/2024/foto-05-2024-min.jpg',
		alt: 'Hjaelmaren',
		location: 'Hjälmaren',
		device: 'Canon AE-1',
	},
	{
		src: '/images/2024/foto-04-2024-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Canon AE-1',
	},
	{
		src: '/images/2024/foto-03-2024-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Canon AE-1',
	},
	{
		src: '/images/2024/foto-02-2024-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Canon AE-1',
	},
	{
		src: '/images/2024/foto-01-2024-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Canon AE-1',
	},
	{
		src: '/images/2023/foto-06-2023-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Canon AE-1',
	},
	{
		src: '/images/2023/foto-05-2023-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Canon AE-1',
	},
	{
		src: '/images/2023/foto-04-2023-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Canon AE-1',
	},
	{
		src: '/images/2023/foto-03-2023-min.jpg',
		alt: 'Berlin',
		location: 'Berlin',
		device: 'Canon AE-1',
	},
	{
		src: '/images/2023/foto-02-2023-min.jpg',
		alt: 'Lubmin',
		location: 'Lubmin',
		device: 'Canon AE-1',
	},
	{
		src: '/images/2023/foto-01-2023-min.jpg',
		alt: 'Lubmin',
		location: 'Lubmin',
		device: 'Canon AE-1',
	},
];

export default photos;
